#!/bin/sh

for i in 3 4 5 6 7 8 9 10 11 12 13
do
cat > DM_kp_$i.in << EOF

&CONTROL
    calculation = 'scf'
    restart_mode = 'from_scratch'
    prefix = 'DM'
    pseudo_dir = './../'
    outdir = './outdir/'
/
&SYSTEM
    ibrav = 2, A = 3.57, nat = 2, ntyp = 1,
    ecutwfc = 75,
    ecutrho = 400,
    occupations = "smearing" , smearing = "gaussian" , degauss = 0.01D0,
/
&ELECTRONS
    electron_maxstep = 100,
    mixing_beta = 0.7,
    conv_thr = 1.0d-6,
/
ATOMIC_SPECIES
 C 12.0107 C.pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS {crystal}
  C  0.000000  0.000000  0.000000
  C  0.250000  0.250000  0.250000

K_POINTS {automatic}
$i $i $i 0 0 0

EOF

../../../qe-7.0/bin/pw.x <DM_kp_$i.in> DM_kp_$i.out

done

rm Etot
rm time

for j in 3 4 5 6 7 8 9 10 11 12 13
do
    echo "for n of kp = $j $j $j" 
    grep ! DM_kp_$j.out  
    grep ! DM_kp_$j.out >> Etot
    grep PWSCF DM_kp_$j.out >> time

done


