#!/bin/sh

cat > nscf_DM_a_3.0.in << EOF

&CONTROL
    calculation = 'nscf'
    restart_mode = 'from_scratch'
    prefix = 'DM_a_3.0'
    pseudo_dir = './../'
    outdir = './outdir/'
/
&SYSTEM
    ibrav = 2, A = 3.0, nat = 2, ntyp = 1,
    ecutwfc = 75,
    ecutrho = 400,
    nbnd = 40,
    occupations = 'tetrahedra',
/
&ELECTRONS
    electron_maxstep = 100,
    mixing_beta = 0.7,
    conv_thr = 1.0d-6,
/
ATOMIC_SPECIES
 C 12.0107 C.pbe-n-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS {crystal}
  C  0.000000  0.000000  0.000000
  C  0.250000  0.250000  0.250000

K_POINTS {automatic}
18 18 18 0 0 0

EOF

../../../qe-7.0/bin/pw.x <nscf_DM_a_3.0.in> nscf_DM_a_3.0.out

